version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # case a release for non-dev-deps
      prefix: fix(deps)
      # no release for dev-ops
      prefix-development: chore(dev-deps)
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
